apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sock-shop
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deployment/applications/sock-shop
  prune: true
  dependsOn:
    - name: contour
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: contour
      namespace: contour
  sourceRef:
    kind: GitRepository
    name: quick-bites
