apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/gateway.yaml

namespace: minecraft

helmCharts:
  - name: minecraft
    releaseName: my
    repo: https://itzg.github.io/minecraft-server-charts/
    version: 4.23.2
    valuesInline:
      minecraftServer:
        eula: "true"
