# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin

release:
  disable: true

blobs:
  - provider: gs
    bucket: gorleaser-quickbites
  - provider: azblob
    bucket: gorleaser-quickbites
  - provider: s3
    bucket: gorleaser-quickbites
    region: eu-central-1