apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: opencost-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://opencost.github.io/opencost-helm-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opencost
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: opencost
  install:
    crds: CreateReplace
    createNamespace: true
  chart:
    spec:
      chart: opencost
      version: 1.27.0
      sourceRef:
        kind: HelmRepository
        name: opencost-charts
        namespace: flux-system
      interval: 10m
  values:
    extraVolumes:
    - name: service-key-secret
      secret:
        secretName: azure-service-key
    opencost:
      exporter:
        extraVolumeMounts:
        - mountPath: /var/secrets
          name: service-key-secret
      prometheus:
        internal:
          enabled: true
          serviceName: prometheus-prometheus-server
          namespaceName: prometheus
      ui:
        enabled: true
