apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: prometheus
  install:
    crds: CreateReplace
    createNamespace: true
  chart:
    spec:
      chart: prometheus
      version: 25.8.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-charts
        namespace: flux-system
      interval: 10m
  values:
    prometheus-pushgateway:
      enabled: false
    alertmanager:
      enabled: false
    extraScrapeConfigs: |
      - job_name: opencost
        honor_labels: true
        scrape_interval: 1m
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        dns_sd_configs:
        - names:
          - opencost.opencost
          type: 'A'
          port: 9003  
